# -*- coding: utf-8 -*-
"""Copy of nsTags_Estimator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YtKjv4DDeC8UE1Ea59rMwo-1nWIaeelp
"""

import streamlit as st
import boto3
import pandas as pd
import json
import plotly.express as px
from datetime import datetime, timedelta

# ==========================================
# 🎨 UI CONFIGURATION
# ==========================================
st.set_page_config(page_title="nsTags Dashboard", page_icon="🛍️", layout="wide")
st.title("🛍️ nsTags Store Analytics")
st.markdown("Real-time footfall, proximity tracking, and brand distribution.")

# ==========================================
# ☁️ AWS CONFIGURATION
# ==========================================
BUCKET_NAME = 'nstags-datalake-hq-2026'
REGION = 'ap-south-1'

# ==========================================
# ⚙️ DATA UNPACKING ENGINE
# ==========================================
@st.cache_data(ttl=60) # Caches data for 60 seconds to optimize AWS S3 requests
def load_s3_data():
    # Securely fetch AWS keys from Streamlit's encrypted secrets vault
    try:
        s3 = boto3.client(
            's3',
            region_name=REGION,
            aws_access_key_id=st.secrets["AWS_ACCESS_KEY_ID"],
            aws_secret_access_key=st.secrets["AWS_SECRET_ACCESS_KEY"]
        )
    except Exception as e:
        st.error("⚠️ AWS Credentials not found. Please add them to Streamlit Secrets.")
        return pd.DataFrame()

    # Grab the 5 most recent 10-minute batches from the Data Lake
    try:
        response = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix='footfall/')
        if 'Contents' not in response:
            return pd.DataFrame()

        files = sorted(response['Contents'], key=lambda x: x['LastModified'], reverse=True)[:5]
    except Exception as e:
        st.error(f"AWS Data Lake Connection Error: {e}")
        return pd.DataFrame()

    all_records = []

    # Unpack the heavily compressed arrays back into readable metrics
    for file in files:
        obj = s3.get_object(Bucket=BUCKET_NAME, Key=file['Key'])
        lines = obj['Body'].read().decode('utf-8').strip().split('\n')

        for line in lines:
            if not line: continue
            try:
                data = json.loads(line)
                store_id = data.get('S', 'Unknown')

                # The timestamp in the JSON is when the batch arrived at AWS
                end_time = datetime.fromtimestamp(data['timestamp'] / 1000.0)
                snapshots = data.get('D', [])

                # Back-calculate the exact time for each 5-second snapshot
                start_time = end_time - timedelta(seconds=len(snapshots)*5)

                for idx, snap in enumerate(snapshots):
                    if len(snap) < 20: continue
                    snap_time = start_time + timedelta(seconds=idx*5)

                    all_records.append({
                        'Store ID': store_id,
                        'Time': snap_time,
                        'Far': snap[0],
                        'Mid': snap[1],
                        'Near': snap[2],
                        'Total Traffic': snap[0] + snap[1] + snap[2],
                        'Apple': snap[17],
                        'Samsung': snap[18],
                        'Other': snap[19]
                    })
            except Exception as e:
                pass # Skip any corrupted lines seamlessly

    # Convert everything into a beautiful Pandas DataFrame for charting
    df = pd.DataFrame(all_records)
    if not df.empty:
        df = df.sort_values('Time')
    return df

# ==========================================
# 📊 DASHBOARD RENDER LOGIC
# ==========================================
with st.spinner("Fetching live Data Lake metrics..."):
    df = load_s3_data()

if df.empty:
    st.warning("⚠️ No data found in the S3 Bucket or waiting for the first 15-minute batch to arrive.")
else:
    # --- SIDEBAR STORE FILTER ---
    st.sidebar.header("Store Selection")
    stores = df['Store ID'].unique()
    selected_store = st.sidebar.selectbox("Select Store MAC Address", stores)

    store_df = df[df['Store ID'] == selected_store]

    # --- TOP KPI CARDS ---
    st.markdown("### ⚡ Live Pulse (Last 10 Minutes)")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Peak Devices", int(store_df['Total Traffic'].max()))
    c2.metric("Apple Devices", int(store_df['Apple'].max()))
    c3.metric("Samsung Devices", int(store_df['Samsung'].max()))
    c4.metric("Near Proximity", int(store_df['Near'].max()))

    st.divider()

    # --- FOOTFALL TREND CHART ---
    st.markdown("### 📈 Footfall Proximity Trends")
    fig_traffic = px.area(
        store_df,
        x='Time',
        y=['Far', 'Mid', 'Near'],
        color_discrete_sequence=['#81C995', '#FDE293', '#F28B82'],
        labels={'value': 'Number of Devices', 'variable': 'Proximity Zone'}
    )
    # Make the chart look premium and transparent
    fig_traffic.update_layout(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig_traffic, use_container_width=True)

    # --- BRAND DISTRIBUTION CHART ---
    st.markdown("### 📱 Device Brand Distribution")
    brand_df = store_df[['Apple', 'Samsung', 'Other']].mean().reset_index()
    brand_df.columns = ['Brand', 'Average Count']
    fig_brands = px.pie(
        brand_df,
        values='Average Count',
        names='Brand',
        hole=0.4,
        color_discrete_sequence=['#E8EAED', '#8AB4F8', '#9AA0A6']
    )
    fig_brands.update_layout(plot_bgcolor='rgba(0,0,0,0)', paper_bgcolor='rgba(0,0,0,0)')
    st.plotly_chart(fig_brands, use_container_width=True)

    # --- RAW DATA EXPANDER ---
    with st.expander("View Raw Analytics Engine Data"):
        st.dataframe(store_df.tail(20), use_container_width=True)